-- Solutions Database Table Structure

CREATE TABLE IF NOT EXISTS `solutions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `solution_id` VARCHAR(50) NOT NULL,
  `hero_title` TEXT NOT NULL,
  `hero_description` TEXT NOT NULL,
  `hero_image_url` VARCHAR(255) NOT NULL,
  `intro_text` TEXT NOT NULL,
  `feature1_title` TEXT NOT NULL,
  `feature1_description` TEXT NOT NULL,
  `feature1_image_url` VARCHAR(255) NOT NULL,
  `feature2_title` TEXT NOT NULL,
  `feature2_features` TEXT NOT NULL,
  `feature2_image_url` VARCHAR(255) NOT NULL,
  `feature3_title` TEXT NOT NULL,
  `feature3_features` TEXT NOT NULL,
  `feature3_image_url` VARCHAR(255) NOT NULL,
  `summary_title` TEXT NOT NULL,
  `summary_text` TEXT NOT NULL,
  `cta_title` TEXT NOT NULL,
  `cta_text` TEXT NOT NULL,
  `cta_button1_text` VARCHAR(100) NOT NULL,
  `cta_button1_link` VARCHAR(255) NOT NULL,
  `cta_button2_text` VARCHAR(100) NOT NULL,
  `cta_button2_link` VARCHAR(255) NOT NULL,
  `date_created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `date_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `solution_id` (`solution_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Sample data for Solution A
INSERT INTO `solutions` (`solution_id`, `hero_title`, `hero_description`, `hero_image_url`, `intro_text`, `feature1_title`, `feature1_description`, `feature1_image_url`, `feature2_title`, `feature2_features`, `feature2_image_url`, `feature3_title`, `feature3_features`, `feature3_image_url`, `summary_title`, `summary_text`, `cta_title`, `cta_text`, `cta_button1_text`, `cta_button1_link`, `cta_button2_text`, `cta_button2_link`) 
VALUES 
('solution-a', 
'Insurance Business Process Outsourcing & Implementation Solutions', 
'Backsure Global Support\'s extensive suite of complementary services provides the extra power you need to give every facet of your insurance business a competitive cutting edge, and take you to the next level of security, agility, and scale.', 
'/api/placeholder/600/500', 
'We\'re bridging borders to deliver seamless insurance support services tailored to your unique processes. De-risk your operations with our proven implementation expertise and close the gap in talent and infrastructure through customized Business Process Outsourcing. Let your internal teams focus on innovation while our dedicated support staff handle the day-to-day with precision and reliability.', 
'Dedicated Employee Support', 
'Scale your business with confidence through Backsure\'s Dedicated Employee Support model. Our professionals work exclusively within your processes and systems, ensuring seamless integration with your operations.', 
'/api/placeholder/450/450', 
'Our Solutions', 
'[{"title":"Sales Support","description":"Lead follow-ups, policy explanations, and client coordination"},{"title":"Underwriting Assistance","description":"Document verification & coordination"},{"title":"Policy Processing & Renewals","description":"End-to-end policy lifecycle support"},{"title":"Claims Coordination","description":"Liaison for clients, insurers, TPAs"},{"title":"CRM Management","description":"Clean data in Zoho, Salesforce, etc."},{"title":"Quote Preparation","description":"Comparative quote prep"},{"title":"Data Entry & Reporting","description":"MIS summaries, dashboards"}]', 
'/api/placeholder/450/450', 
'Why Backsure Global Support', 
'[{"title":"Industry-Trained Teams","description":"Experts trained in insurance workflows"},{"title":"Operational Cost Savings","description":"Scale without in-house hiring"},{"title":"Better Client Experience","description":"Smooth, accurate journeys from quote to claim"}]', 
'/api/placeholder/450/450', 
'Insurance Support That Works Like Your In-House Team', 
'Choose Backsure Global Support to power your insurance operations with reliable, trained, and performance-driven backend teams. Our experts work closely with your team to integrate new systems, processes, or offshore support with minimal disruption. Flexibility, domain focus, and fast turnaround are our core strengths.', 
'Ready to Scale Smarter?', 
'Let\'s create a custom support model for your business.', 
'Talk to an Expert', 
'contact.html', 
'Talk to Us', 
'contact.html');

-- Sample data for Solution B (placeholder content)
INSERT INTO `solutions` (`solution_id`, `hero_title`, `hero_description`, `hero_image_url`, `intro_text`, `feature1_title`, `feature1_description`, `feature1_image_url`, `feature2_title`, `feature2_features`, `feature2_image_url`, `feature3_title`, `feature3_features`, `feature3_image_url`, `summary_title`, `summary_text`, `cta_title`, `cta_text`, `cta_button1_text`, `cta_button1_link`, `cta_button2_text`, `cta_button2_link`) 
VALUES 
('solution-b', 
'Finance & Accounting Support Services', 
'Strengthen your financial operations with specialized accounting support. Our dedicated teams handle everything from routine bookkeeping to complex financial analysis, freeing your core team to focus on strategic decision-making.', 
'/api/placeholder/600/500', 
'Backsure\'s finance and accounting services help businesses of all sizes streamline their financial operations, reduce costs, and improve accuracy. Our specialists become an extension of your team, working within your systems and following your processes.', 
'Comprehensive Financial Support', 
'From day-to-day bookkeeping to month-end closing and financial reporting, our teams provide the complete spectrum of accounting support tailored to your industry requirements and organizational structure.', 
'/api/placeholder/450/450', 
'Core Accounting Services', 
'[{"title":"Accounts Payable Processing","description":"Invoice processing, payment approvals, vendor management"},{"title":"Accounts Receivable Management","description":"Client invoicing, collections, aging analysis"},{"title":"General Ledger Maintenance","description":"Journal entries, reconciliations, financial close"},{"title":"Payroll Processing","description":"Time tracking, tax calculations, payment processing"},{"title":"Financial Reporting","description":"Standard and custom reports, dashboards, analysis"},{"title":"Tax Preparation Support","description":"Document organization, data compilation, filing assistance"}]', 
'/api/placeholder/450/450', 
'Why Choose Our Finance Solutions', 
'[{"title":"Specialized Expertise","description":"Certified accountants with industry-specific knowledge"},{"title":"Cost Efficiency","description":"Reduce operational expenses by 40-60%"},{"title":"Scalable Support","description":"Easily adjust resources as your business grows"},{"title":"Enhanced Controls","description":"Improved compliance and financial governance"}]', 
'/api/placeholder/450/450', 
'Financial Operations Built for Growth', 
'Our finance and accounting solutions adapt to your changing business needs, providing the right level of support at every stage of your organization\'s development. We implement best practices while working within your established systems and processes.', 
'Transform Your Financial Operations', 
'Discuss how our accounting solutions can strengthen your business foundation.', 
'Request a Consultation', 
'contact.html', 
'Learn More', 
'finance-accounting.html');

-- Sample data for Solution C (placeholder content)
INSERT INTO `solutions` (`solution_id`, `hero_title`, `hero_description`, `hero_image_url`, `intro_text`, `feature1_title`, `feature1_description`, `feature1_image_url`, `feature2_title`, `feature2_features`, `feature2_image_url`, `feature3_title`, `feature3_features`, `feature3_image_url`, `summary_title`, `summary_text`, `cta_title`, `cta_text`, `cta_button1_text`, `cta_button1_link`, `cta_button2_text`, `cta_button2_link`) 
VALUES 
('solution-c', 
'Human Resources & Administrative Support', 
'Transform your HR operations with tailored administrative support from Backsure. Our dedicated teams handle routine tasks and processes, allowing your internal HR professionals to focus on strategic initiatives and employee development.', 
'/api/placeholder/600/500', 
'From recruitment support to employee onboarding and benefits administration, our HR specialists work as an extension of your team. We adapt to your existing processes and systems while bringing best practices that enhance efficiency and compliance.', 
'Strategic HR Support', 
'Our HR support solutions go beyond basic administration to include everything from recruitment assistance to performance management systems. We implement the right mix of human expertise and technological tools to optimize your HR function.', 
'/api/placeholder/450/450', 
'HR Administrative Services', 
'[{"title":"Recruitment Support","description":"Job posting, resume screening, interview coordination"},{"title":"Employee Onboarding","description":"Documentation, orientation materials, benefits enrollment"},{"title":"HR Documentation","description":"Policy updates, employee handbooks, compliance checklists"},{"title":"Benefits Administration","description":"Enrollment support, claims processing, vendor management"},{"title":"Leave Management","description":"Time-off tracking, absence monitoring, return coordination"},{"title":"Employee Data Management","description":"HRIS maintenance, reporting, analytics"}]', 
'/api/placeholder/450/450', 
'The Backsure HR Advantage', 
'[{"title":"HR Expertise","description":"Professionals with multi-industry HR experience"},{"title":"Compliance Focus","description":"Up-to-date knowledge of regulations and requirements"},{"title":"Technology Integration","description":"Seamless work with your existing HRIS platforms"},{"title":"Employee Experience","description":"Improved service delivery for your workforce"}]', 
'/api/placeholder/450/450', 
'HR Support That Elevates Your People Strategy', 
'By handling routine HR tasks with precision and care, our teams free your internal HR leaders to focus on strategic initiatives that drive employee engagement, development, and retention. We become your reliable HR operations partner while you shape your organization\'s future.', 
'Elevate Your HR Function', 
'Discover how our dedicated HR support can transform your people operations.', 
'Schedule a Consultation', 
'contact.html', 
'Explore Services', 
'hr-support.html');

-- Sample data for Solution D (placeholder content)
INSERT INTO `solutions` (`solution_id`, `hero_title`, `hero_description`, `hero_image_url`, `intro_text`, `feature1_title`, `feature1_description`, `feature1_image_url`, `feature2_title`, `feature2_features`, `feature2_image_url`, `feature3_title`, `feature3_features`, `feature3_image_url`, `summary_title`, `summary_text`, `cta_title`, `cta_text`, `cta_button1_text`, `cta_button1_link`, `cta_button2_text`, `cta_button2_link`) 
VALUES 
('solution-d', 
'Customer Service & Support Solutions', 
'Enhance your customer experience with Backsure\'s dedicated customer service teams. We provide responsive, knowledgeable support that represents your brand values while efficiently resolving customer inquiries across all channels.', 
'/api/placeholder/600/500', 
'Our customer service specialists become true extensions of your brand, thoroughly trained in your products, services, and company culture. We handle everything from routine inquiries to complex issue resolution, ensuring customers receive consistent, high-quality support that builds loyalty and satisfaction.', 
'Customer-Focused Support', 
'Our approach to customer service combines human empathy with efficient process management. We develop deep knowledge of your products and services to provide accurate, helpful responses that reflect your brand voice and values.', 
'/api/placeholder/450/450', 
'Comprehensive Support Channels', 
'[{"title":"Phone Support","description":"Inbound/outbound call handling with custom scripts"},{"title":"Email Management","description":"Prompt, professional correspondence and follow-up"},{"title":"Live Chat Support","description":"Real-time assistance on your website or app"},{"title":"Social Media Monitoring","description":"Response to inquiries and mentions across platforms"},{"title":"Ticketing System Management","description":"Issue tracking, escalation, and resolution coordination"},{"title":"Self-Service Knowledge Base","description":"Content development and maintenance"}]', 
'/api/placeholder/450/450', 
'Why Our Customer Service Solutions Excel', 
'[{"title":"Brand Alignment","description":"Representatives who embody your company culture"},{"title":"Multi-Channel Expertise","description":"Seamless support across all customer touchpoints"},{"title":"Quality Assurance","description":"Rigorous monitoring and continuous improvement"},{"title":"Customer Insights","description":"Valuable feedback collection and trend analysis"}]', 
'/api/placeholder/450/450', 
'Customer Service That Strengthens Your Brand', 
'Our support teams don\'t just resolve issues—they create positive experiences that build customer loyalty and enhance your reputation. By combining technical knowledge with authentic human connection, we help turn everyday interactions into opportunities to strengthen customer relationships.', 
'Elevate Your Customer Experience', 
'Let\'s discuss how our support solutions can enhance your customer relationships.', 
'Talk to a Specialist', 
'contact.html', 
'View Case Studies', 
'customer-service.html');